// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DirectLine.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Parameters for creating a token
    /// </summary>
    public partial class TokenParameters
    {
        /// <summary>
        /// Initializes a new instance of the TokenParameters class.
        /// </summary>
        public TokenParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TokenParameters class.
        /// </summary>
        /// <param name="user">User account to embed within the token</param>
        public TokenParameters(ChannelAccount user = default(ChannelAccount), string eTag = default(string))
        {
            User = user;
            ETag = eTag;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets user account to embed within the token
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public ChannelAccount User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eTag")]
        public string ETag { get; set; }

    }
}
